import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service - SoulMate.ai",
  description: "Terms of Service for SoulMate.ai",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 pb-16 pt-8">
      <Link href="/" className="mb-8 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors">
        <ArrowLeft className="h-4 w-4" /> Back to Home
      </Link>

      <h1 className="mb-2 text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mb-8 text-sm text-muted-foreground">Last updated: June 3, 2026</p>

      <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
        <section>
          <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
          <p>By using SoulMate.ai, you agree to these Terms. If you do not agree, do not use the service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">2. Age Requirement</h2>
          <p>You must be at least 18 years old to create an account. Certain features may have additional age restrictions.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">3. AI-Generated Content</h2>
          <p>Conversations with your AI companion are generated by artificial intelligence. SoulMate.ai makes no guarantees about the accuracy, appropriateness, or safety of AI-generated responses. Use discretion.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Use the service for illegal activities</li>
            <li>Generate or share harmful, abusive, or sexually explicit content</li>
            <li>Reverse engineer or attempt to extract the AI models</li>
            <li>Bypass usage limits or subscription controls</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold">5. Purchases & Billing</h2>
          <p>All plans are one-time purchases. There are no recurring charges or automatic renewals. See our <Link href="/refund-policy" className="text-brand-purple hover:underline">Refund Policy</Link> for refund terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">6. Termination</h2>
          <p>We may suspend or terminate your account for violations of these Terms. You may delete your account at any time.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">7. Disclaimer</h2>
          <p>SoulMate.ai is provided "as is" without warranties of any kind. We are not responsible for emotional reliance on AI companions.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">8. Contact</h2>
          <p><a href="mailto:support@soulmate.ai" className="text-brand-purple hover:underline">support@soulmate.ai</a></p>
        </section>
      </div>
    </div>
  );
}
